### ISSUE TITLE
BedrockifierCLI doesn't appear to close

### ISSUE THREAD

**Issue by DanTheMan827** [Kaiede/docker-minecraft-bedrock-backup#12]
It seems that the docker container fails to loop because `BedrockifierCLI` never terminates.

```
BACKUP_INTERVAL=3h
UID=0
GID=100
```

**config.json:**
```json
{
    "servers": {
        "mcbedrock": "/server/worlds"
    },
    "trim": {
        "trimDays":   2,
        "keepDays":   14,
        "minKeep":    2
    }
}
```

**Paths shared:**
```
/server
/backups
/var/run/docker.sock
```

**Comment by Kaiede** [comment]
Can you share the logs from the docker container? This isn’t enough information to diagnose the problem.

**Comment by DanTheMan827** [comment]
Here's the output from the server container
```
.
Data saved. Files are now ready to be copied.
Rad World/db/MANIFEST-002308:24465, Rad World/db/CURRENT:16, Rad World/db/002311.ldb:2127021, Rad World/db/002312.ldb:2141799, Rad World/db/002313.ldb:2120594, Rad World/db/002314.ldb:2120578, Rad World/db/002315.ldb:2123246, Rad World/db/002316.ldb:2125002, Rad World/db/002317.ldb:2144494, Rad World/db/002318.ldb:2121830, Rad World/db/002319.ldb:2059365, Rad World/db/002807.ldb:67249, Rad World/db/002809.ldb:239, Rad World/db/002811.ldb:239, Rad World/db/002812.log:144, Rad World/db/002813.ldb:239, Rad World/level.dat:2509, Rad World/level.dat_old:2509, Rad World/levelname.txt:14
Changes to the level are resumed.
Changes to the level are resumed.
```
This is the output from the backup container
```
time="2021-11-27T19:01:15-06:00" level=debug msg="Forwarding signal" signal=terminated
time="2021-11-27T19:01:15-06:00" level=debug msg="Sending message on stdin due to SIGTERM" message=stop
time="2021-11-27T19:01:29-06:00" level=debug msg="Using /backups to match uid and gid"
time="2021-11-27T19:01:29-06:00" level=debug msg="Resolved 0 from environment variable UID"
time="2021-11-27T19:01:29-06:00" level=debug msg="Resolved 100 from environment variable GID"
time="2021-11-27T19:01:29-06:00" level=debug msg="stdin is detached, so forwarding is disabled"
Performing Backups
[ PTYProcess:sh ] [ TRACE ] Launching (PTYKit/PTYProcess.swift:72)
[ PTYProcess:sh ] [ TRACE ] Sending: save hold
(PTYKit/PTYProcess.swift:97)
[ PTYProcess:sh ] [ TRACE ] Expecting: ["Saving", "The command is already running"] (PTYKit/PTYProcess.swift:120)
[ PTYProcess:sh ] [ TRACE ] Starting RunLoop (PTYKit/PTYProcess.swift:123)
[ PTYProcess:sh ] [ TRACE ] Background Reading Start (PTYKit/PTYProcess.swift:162)
[ PTYProcess:sh ] [ TRACE ] Content Read: Saving...
(PTYKit/PTYProcess.swift:147)
[ PTYProcess:sh ] [ TRACE ] Match Found (PTYKit/PTYProcess.swift:151)
[ PTYProcess:sh ] [ TRACE ] Background Reading Stop (PTYKit/PTYProcess.swift:177)
[ PTYProcess:sh ] [ TRACE ] Background Reading Cleanup (PTYKit/PTYProcess.swift:170)
[ PTYProcess:sh ] [ TRACE ] Sending: save query
(PTYKit/PTYProcess.swift:97)
[ PTYProcess:sh ] [ TRACE ] Expecting: ["Files are now ready to be copied"] (PTYKit/PTYProcess.swift:120)
[ PTYProcess:sh ] [ TRACE ] Starting RunLoop (PTYKit/PTYProcess.swift:123)
[ PTYProcess:sh ] [ TRACE ] Background Reading Start (PTYKit/PTYProcess.swift:162)
[ PTYProcess:sh ] [ TRACE ] Content Read: Data saved. Files are now ready to be copied.
Rad World/db/MANIFEST-002308:24465, Rad World/db/CURRENT:16, Rad World/db/002311.ldb:2127021, Rad World/db/002312.ldb:2141799, Rad World/db/002313.ldb:2120594, Rad World/db/002314.ldb:2120578, Rad World/db/002315.ldb:2123246, Rad World/db/002316.ldb:2125002, Rad World/db/002317.ldb:2144494, Rad World/db/002318.ldb:2121830, Rad World/db/002319.ldb:2059365, Rad World/db/002807.ldb:67249, Rad World/db/002809.ldb:239, Rad World/db/002811.ldb:239, Rad World/db/002812.log:144, Rad World/db/002813.ldb:239, Rad World/level.dat:2509, Rad World/level.dat_old:2509, Rad World/levelname.txt:14
(PTYKit/PTYProcess.swift:147)
[ PTYProcess:sh ] [ TRACE ] Match Found (PTYKit/PTYProcess.swift:151)
[ PTYProcess:sh ] [ TRACE ] Background Reading Stop (PTYKit/PTYProcess.swift:177)
[ PTYProcess:sh ] [ TRACE ] Background Reading Cleanup (PTYKit/PTYProcess.swift:170)
Starting Backup of worlds at: /server/worlds
Backing Up: Robert's World
Backed up as: Robert's World.20211127-190129.mcworld
Backup Complete...
[ PTYProcess:sh ] [ TRACE ] Sending: save resume
(PTYKit/PTYProcess.swift:97)
[ PTYProcess:sh ] [ TRACE ] Expecting: ["Changes to the level are resumed", "A previous save has not been completed"] (PTYKit/PTYProcess.swift:120)
[ PTYProcess:sh ] [ TRACE ] Starting RunLoop (PTYKit/PTYProcess.swift:123)
[ PTYProcess:sh ] [ TRACE ] Background Reading Start (PTYKit/PTYProcess.swift:162)
[ PTYProcess:sh ] [ TRACE ] Content Read: Changes to the level are resumed.
(PTYKit/PTYProcess.swift:147)
[ PTYProcess:sh ] [ TRACE ] Match Found (PTYKit/PTYProcess.swift:151)
[ PTYProcess:sh ] [ TRACE ] Background Reading Stop (PTYKit/PTYProcess.swift:177)
[ PTYProcess:sh ] [ TRACE ] Background Reading Cleanup (PTYKit/PTYProcess.swift:170)
[ PTYProcess:sh ] [ TRACE ] Sending: Q (PTYKit/PTYProcess.swift:97)
```

**Comment by Kaiede** [comment]
> It appears that Q isn't properly detaching from the container... 

Yes, that does seem to be the case. I do notice that your create command doesn't include '-t' to create the pseudo tty, though. Detaching in the way that BedrockifierCLI was designed requires the pseudo tty that is brought up in the documentation for the `itzg/minecraft-bedrock-server` container. 

> perhaps running docker attach --sig-proxy=false and just sending the interrupt signal to the process would be better to detach than using detach-keys?

That would take some time to implement and test, but is worth considering as an enhancement.

**Comment by DanTheMan827** [comment]
Ah yes, you’re right.

the missing TTY prevented it from detaching, although if I enable a pseudo TTY it makes the log less readable from the unraid interface

aside from detaching though, everything else does work as expected with just the `-I` option

sorry for any confusion, I’m still learning how unraid works in regards to Docker

**Comment by Kaiede** [comment]
Yeah, no worries, it's still useful details. I'm going to keep this open so I can see if I can remove the PTY requirement, or better document it. One or the other.

**Comment by DanTheMan827** [comment]
All that is really needed is `-i`, but the way you terminate the Docker attach changes depending on if you have a TTY or just standard input/out

TTY needs a detach sequence, non-TTY needs `--sig-proxy=false` with a standard sigterm to detach

**Comment by Kaiede** [comment]
The fixes for this have just got merged, and will show up in the new `test` tag shortly. It will show up in the latest tag after a few days when I've gotten the chance to let them run on my own server.

**Comment by DanTheMan827** [comment]
Looking at the code, it seems like it should work...

But I didn't see any line where usePty is set beyond a static value of `false`

If you kill the docker process with a pty attached, it will forward that signal to the docker process

I'm not sure if there's a way you can check the container options before attaching to determine if a pty is attached or not

**Comment by Kaiede** [comment]
You don’t have to use a TTY-enabled pipe even if the container is TTY enabled.

`usePty` is a rudimentary gate on the functionality. I was using it for testing, primarily. `let` in Swift is used for constants, so it will always be false right now, and the dead code stripped. If I don’t find a good use for using a TTY when attaching to the docker container in the future, I’ll likely remove the functionality as part of a later cleanup.

**Comment by DanTheMan827** [comment]
Yes, but if the container is TTY enabled, you can't terminate the docker attach command as a means to detach because `--sig-proxy=false` only works if the container doesn't have a tty enabled.

**Comment by Kaiede** [comment]
> If I were to install this test build without changing the options for my server container, it would terminate the server after finishing the backup instead of just detaching from it.

My local tests included checking with tty on and off on the server container, precisely because I can’t assume folks will be able to change their settings on a random pull. And it’s not the behavior I’m seeing on my own server with tty enabled, which I use to dispatch admin commands without having to bring up a full client. On top of that, I’ve been running at least 24hrs each with TTY false, and TTY true on my local server as a smoke test, with the same results in each case of getting the usual 8 backups each, and with the uptime on both services being what I expect at the end of the run. 

If what you say was happening, this would have been caught when I was doing the work initially under the dev tag. Especially since such behavior would be immediately apparent: the server would reset during startup due to the initial backup which would appear in the health reporting, logs, and even the console when using `docker-compose up` without -d to verify behaviors. 

But you got me curious so I read the docker attach source. Not super familiar with some of the specific syntax Go likes to use for gluing event sources to sinks (which is relevant), but this bit is rather interesting:

```
if opts.proxy && !c.Config.Tty {
    sigc := notifyAllSignals()
    go ForwardAllSignals(ctx, dockerCli, opts.container, sigc)
    defer signal.StopCatch(sigc)
}
```

If the container being attached to is configured for TTY, signal proxying in the sense of proxying signals sent to the `docker attach` process is completely disabled as the event source is not configured to be sunk to the container, which is done by ForwardAllSignals. Instead it relies on the escape sequences being sent on the TTY pipe to the container that way. So yes, --sig-proxy is ignored if TTY is true, but so are the signals themselves. This aligns with the testing I’ve done, and this particular bit is present in both the docker-ce repo and the cli repo, meaning it hasn’t changed in quite a while. Since I’m not sending escape sequences to terminate the attach (which doesn’t work without a TTY in the first place), it’s not getting forwarded.

If anything I hope this stresses the importance of empirical testing during development. :)

**Comment by DanTheMan827** [comment]
Well now I feel like a dummy... 😅

I guess CTRL+C inside of docker attach isn't the same as sending that process the kill signal...

**Comment by DanTheMan827** [comment]
Just FYI, it does work, but after every backup it complains about the docker process being unexpectedly terminated
```
[ BedrockifierCLI:WorldBackup ] [ DEBUG ] Terminating Docker Process (Bedrockifier/Model/WorldBackup.swift:70)
[ PTYProcess:docker ] [ INFO ] Unexpected Process Termination: /usr/bin/docker (PTYKit/PTYProcess.swift:80)
```

Again, not a huge deal but I thought I'd bring it to your attention

I'm launching the container without tty by the way.

**Comment by Kaiede** [comment]
Yeah, that’s a side effect of a default handler I added in PTYKit a while ago.

PTYKit was re-written to avoid a file descriptor leak in Swift on Linux as part of the work to stand up `bedrockifierd` (and was important to standing up the event listening logic), which shouldn’t produce that spurious notification anymore.
