### ISSUE TITLE
different permissions error

### ISSUE THREAD

**Issue by edward3h** [Kaiede/docker-minecraft-bedrock-backup#2]
I've looked at the readme and issue #1 and I'm still confused about this.

    backup_1      | time="2021-06-03T08:15:20-04:00" level=debug msg="Using /backups to match uid and gid"
    backup_1      | time="2021-06-03T08:15:20-04:00" level=debug msg="Resolved UID=1000 from match path"
    backup_1      | time="2021-06-03T08:15:20-04:00" level=debug msg="Resolved GID=1000 from match path"
    backup_1      | time="2021-06-03T08:15:20-04:00" level=debug msg="stdin is detached, so forwarding is disabled"
    backup_1      | + : /usr/bin/docker
    backup_1      | + : /backups
    backup_1      | + : config.json
    backup_1      | + : 6h
    backup_1      | + true
    backup_1      | + /opt/bedrock/BedrockifierCLI backupjob /backups/config.json --dockerPath /usr/bin/docker --backupPath /backups
    backup_1      | Performing Backups
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Launching (PTYKit/PTYProcess.swift:72)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Sending: save hold
    backup_1      |  (PTYKit/PTYProcess.swift:97)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Expecting: ["Saving", "The command is already running"] (PTYKit/PTYProcess.swift:120)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Starting RunLoop (PTYKit/PTYProcess.swift:123)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Background Reading Start (PTYKit/PTYProcess.swift:162)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Content Read: WARNING: Error loading config file: /root/.docker/config.json: open /root/.docker/config.json: permission denied
    backup_1      |  (PTYKit/PTYProcess.swift:147)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] No Match (PTYKit/PTYProcess.swift:156)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Content Read: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/minecraft1/json: dial unix /var/run/docker.sock: connect: permission denied
    backup_1      |  (PTYKit/PTYProcess.swift:147)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] No Match (PTYKit/PTYProcess.swift:156)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Background Reading Stop (PTYKit/PTYProcess.swift:177)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Terminated (PTYKit/PTYProcess.swift:76)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Background Reading Cleanup (PTYKit/PTYProcess.swift:170)
    backup_1      | The operation could not be completed. (Bedrockifier.WorldBackupError error 0.)
    minecraft_backup_1 exited with code 1

It seems to get the right path to config.json and the right user, but then tries to read `/root/.docker/config.json`

OS: Ubuntu 21.04
Docker version 20.10.7, build f0df350
docker-compose version 1.29.2, build 5becea4c

docker-compose.yml:

    version: "3.9"
    services: 
        minecraft1:
            image: itzg/minecraft-bedrock-server
            restart: "no"
            environment:
              EULA: "TRUE"
              SERVER_NAME: "test docker"
              GAMEMODE: "survival"
              DIFFICULTY: "hard"
              LEVEL_NAME: "test docker"
            ports:
              - 19132:19132/udp
            volumes:
              - "${MC_HOME}/1:/data"
            stdin_open: true
            tty: true
    
        backup:
            image: kaiede/minecraft-bedrock-backup
            restart: "no"
            depends_on:
                - "minecraft1"
            environment:
                DEBUG: "true"
                BACKUP_INTERVAL: "6h"
                TZ: "America/New_York"
            volumes:
                - /var/run/docker.sock:/var/run/docker.sock
                - "${BACKUP_DIR:?err}:/backups"
                - "${MC_HOME}/1:/minecraft1"

config.json:

    {
        "servers": {
            "minecraft1": "/minecraft1/worlds"
        },
    
        "trim": {
            "trimDays":   2,
            "keepDays":   14,
            "minKeep":    2
        }
    }

**Comment by Kaiede** [comment]
Some details on how you have docker configured on the machine/VM would help, since that's where things are falling over here. Is docker run as root, or rootless? Is UID 1000 capable of accessing docker? For installs where docker is run as root, is UID 1000 part of the docker group? Based on the errors, I suspect it's a case where you are running docker as root. So if UID 1000 is part of the docker group, you have two ways to fix this: 

1. `chgrp -r docker ${BACKUP_DIR}`
2. add `GID: <docker GID>` to the environment settings of the backup container (I believe that should still let it read/write the backups dir, and be part of the docker group at the same time).

Unfortunately, getting permissions right is somewhat tricky here, because we want to run the backup with reduced permissions as much as possible, but also need to be able to access docker to attach to other containers. And because what needs to be done varies with each docker install, it's easy for me to miss steps while trying to also cover as much as possible. 

The logging prefixed with `[ PTYProcess:sh ]` is from the phase where BedrockifierCLI is attempting to communicate with the other docker containers. If it's doing this, it loaded `/backups/config.json` just fine, which is good. "PTYProcess" is how  the backup tool launches `docker attach` so it can send the 'save hold' and 'save resume' commands to the server being backed up.

**Comment by edward3h** [comment]
Thanks for looking :)

docker is running as root
id 1000 is my regular user, it's a member of the docker group which is 998. I can run docker commands with this user.

I tried both 1 and 2 from your comment, and also added the UID environment but I still get a similar error.

    Attaching to minecraft_backup_1
    backup_1      | time="2021-06-03T15:37:02-04:00" level=debug msg="Using /backups to match uid and gid"
    backup_1      | time="2021-06-03T15:37:02-04:00" level=debug msg="Resolved 1000 from environment variable UID"
    backup_1      | time="2021-06-03T15:37:02-04:00" level=debug msg="Resolved 998 from environment variable GID"
    backup_1      | time="2021-06-03T15:37:02-04:00" level=debug msg="stdin is detached, so forwarding is disabled"
    backup_1      | + : /usr/bin/docker
    backup_1      | + : /backups
    backup_1      | + : config.json
    backup_1      | + : 6h
    backup_1      | + true
    backup_1      | + /opt/bedrock/BedrockifierCLI backupjob /backups/config.json --dockerPath /usr/bin/docker --backupPath /backups
    backup_1      | Performing Backups
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Launching (PTYKit/PTYProcess.swift:72)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Sending: save hold
    backup_1      |  (PTYKit/PTYProcess.swift:97)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Expecting: ["Saving", "The command is already running"] (PTYKit/PTYProcess.swift:120)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Starting RunLoop (PTYKit/PTYProcess.swift:123)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Background Reading Start (PTYKit/PTYProcess.swift:162)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Content Read: WARNING: Error loading config file: /root/.docker/config.json: open /root/.docker/config.json: permission denied
    backup_1      |  (PTYKit/PTYProcess.swift:147)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] No Match (PTYKit/PTYProcess.swift:156)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Content Read: Error: No such container: minecraft1
    backup_1      |  (PTYKit/PTYProcess.swift:147)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] No Match (PTYKit/PTYProcess.swift:156)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Background Reading Stop (PTYKit/PTYProcess.swift:177)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Terminated (PTYKit/PTYProcess.swift:76)
    backup_1      | [ PTYProcess:sh ] [ TRACE ] Background Reading Cleanup (PTYKit/PTYProcess.swift:170)
    backup_1      | The operation could not be completed. (Bedrockifier.WorldBackupError error 0.)
    minecraft_backup_1 exited with code 1

**Comment by Kaiede** [comment]
Okay you got me curious, and I get the same warning about the docker configuration file in my working system so that seems like a red herring:

```
[ PTYProcess:sh ] [ TRACE ] Sending: save hold
 (PTYKit/PTYProcess.swift:97)
[ PTYProcess:sh ] [ TRACE ] Expecting: ["Saving", "The command is already running"] (PTYKit/PTYProcess.swift:120)
[ PTYProcess:sh ] [ TRACE ] Starting RunLoop (PTYKit/PTYProcess.swift:123)
[ PTYProcess:sh ] [ TRACE ] Background Reading Start (PTYKit/PTYProcess.swift:162)
[ PTYProcess:sh ] [ TRACE ] Content Read: WARNING: Error loading config file: /root/.docker/config.json: open /root/.docker/config.json: permission denied
 (PTYKit/PTYProcess.swift:147)
[ PTYProcess:sh ] [ TRACE ] No Match (PTYKit/PTYProcess.swift:156)
[ PTYProcess:sh ] [ TRACE ] Content Read: save hold
```

In your case, it looks more like this is the new problem:

```
backup_1      | [ PTYProcess:sh ] [ TRACE ] Content Read: Error: No such container: minecraft1
```

I'd check what `docker ps` shows, since based on the log, it sounds like the container itself might have gotten prefixed with `minecraft_` like your backup service did. One annoying thing about docker-compose is that unless you specify the container name manually, it prefixes all containers: `<compose_group_name>_<service_name>`

**Comment by edward3h** [comment]
You got it :)

Added `container_name: minecraft1` in the right place in docker-compose.yml and it works now.

**Comment by Kaiede** [comment]
Thanks. I'll take another pass at the documentation to see if I can clear some things up more.

**Comment by weihao** [comment]
I ran into the same issue and adding container_name solved it.

Thanks @Kaiede
