### ISSUE TITLE
Backups triggered by server events

### ISSUE THREAD

**Issue by Kaiede** [Kaiede/docker-minecraft-bedrock-backup#3]
One thing that would be nice is to have some sort of mechanism for triggering backups based on server events.

* User login
* User logout
* Chat "command" perhaps?

This does require turning the backup tool into a full blown service that attaches to the docker containers and then monitors the server outputs. 

Cron-like behaviors doesn't require this, but this can also enable cron-like behaviors.

**Comment by DanTheMan827** [comment]
It doesn't appear that the server log includes chat or commands used by users like the java version does.

Doing a backup when the last user logs out though would be super handy though, and not doing backups when no user is connected would prevent making backups unnecessarily

**Comment by Kaiede** [comment]
Probably for the best that it doesn’t log chat. The other two I have used with a different tool on Windows to do backups, so I know it’s doable to trigger things based on events like that.

**Comment by Kaiede** [comment]
I've done a good chunk of the work required to make Bedrockifier available as a self-running service (`bedrockifierd`) that runs inside the container instead of a tool that is run on an interval by a script. This doesn't address the original ideas here yet, but does lay the foundation to enable it. The tool has to be able to run as a daemon, attached to the server through a more asynchronous pipe to be able to listen in and act on the events. It needs to handle scheduling, and it needs to be idle when nothing is happening. 

Right now I'm running `bedrockifierd` on my personal Bedrock server with the same sort of interval setting to see how well it plays out over a few days, while I continue working on the rest of the pieces needed. Things that need to be resolved before I can merge in this work:

* PTYKit relies on CFRunLoop when being used on the main thread, so that async events while reading/writing the PTY can still happen on the main thread while it's blocked due to the synchronous API. This design works well for ConsoleKit-based apps where the main thread cannot be reached asynchronously all that well. But with the service, this approach seems to cause every `expect` to time out even when a match is found.
* With Swift 5.5, we can use the new concurrency features to move PTYKit to use async/await patterns instead of synchronous APIs. This should help by moving the keeping work off the main thread as much as possible.

**Comment by DanTheMan827** [comment]
What I would do personally is read every byte of stdout from the docker attach command up until a line break and store them in a buffer, then would send an async event with that buffer converted to string as the argument.

You would end up having many events fire that you likely wouldn't have a response for, but it

**Comment by Kaiede** [comment]
Yeah, I’ll just note that the comments as I post them can get out of date pretty quick. A lot of it is more “stream of consciousness” note taking on my part, so I can remember what I was doing when I come back to this after my day job or after working on another project. 

Now that a good chunk of work has migrated to the test tag, backup scheduling in general is something I’m going to be looking at next. Especially since now that Java is supported, I’m noticing that large worlds can be a bit of a problem and cause some ugly lag spikes even on machines with SSDs. So helping folks get backups made when players aren’t active is going to be a higher priority compared to Bedrock where the server doesn’t take as much of a hit when saving is disabled for a minute.

**Comment by Kaiede** [comment]
Most of the work around event-based backups is done, which includes a lot of refactoring work around the PTYs used to allow for both interval based backups and 

Two events are mostly useful for Bedrock servers where doing backups while players are connected are generally okay.
- onPlayerLogin: true
- onPlayerLogout: true

A third event is useful for Bedrock and Java. 
- onLastLogout: true

And to throttle how many backups this creates per day, there's another schedule setting that limits how frequently any one container can be backed up. This even applies to daily/interval backups, 
- minInterval: 4h

----

However, there are a couple things to investigate before rolling this out to the test tag:
- I'm noticing a couple cases with Bedrock where sending 'save resume' does resume, but it's not received. This doesn't happen all the time, which is a bit worrying. I've made some changes to try to at least make sure backup behavior isn't impacted in the long term when this is hit, but I want some more time to see if I can understand why the string just doesn't seem to make it every so often.
- Similar to the above, there's occasionally a race condition where terminating the `docker attach` process doesn't handle things in the right order and can cause a crash when a callback is executed too late, that got reintroduced I the refactor. I believe this is fixed again, but this sort of bug generally needs bake time to ensure it is actually gone. Unfortunately, it's also possible it is already in the test tag.
- Want to clean up the listener strings a bit to avoid too much duplication.
- Backwards compatibility needs to be re-tested, and general coverage on the new, much larger matrix of things the user can configure.
- In the same vein as the previous item, it turns out that `docker attach` is a pretty expensive process, memory wise. While bedrockifierd takes 20-25MB of RAM, each attach process takes around 50MB on my test VM. I've made some optimizations to only keep these open all the time if the service is configured to listen, but it does mean testing needs to cover both scenarios very explicitly.

**Comment by Kaiede** [comment]
Bake time is looking good so far, can probably move this to the test tag soon:

* See if I can properly terminate the timeout timers when matches are found with the new logic.
* Add `startupDelay` config option?
* Clean up listener strings.
* Test backwards compatibility with existing configs.

**Comment by Kaiede** [comment]
This is now in the test tag. The test tag will likely get moved to latest this weekend after a bit more bake time on my personal servers.
